group "CSharpConcepts/00_CSharpHelloWorld"
	include "00_CSharpHelloWorld/DotNET"
	include "00_CSharpHelloWorld/DotNETWinForm"
	include "00_CSharpHelloWorld/DotNETFramework"
	include "00_CSharpHelloWorld/DotNETFrameworkWPF"
	include "00_CSharpHelloWorld/DotNETWPF"
	include "00_CSharpHelloWorld/DotNETFrameworkWinForms"
group ""
