BindingOutputDir = os.getcwd()

group "CSharpFramework/WPF/Binding"
	include "ADO.NETAsBindingSource"
	include "BindingPath"
	include "ControlAsBindingSrc"
	include "ControlBindingDirAndDataUpdate"
	include "HelloBinding"
	include "LINQAsSource"
	include "MultiBinding"
	include "NoPathBinding"
	include "NoPathSourceBinding"
	include "NoSourceBinding"
	include "ObjectDataProviderAsSource"
	include "RelativeSource"
	include "SetBindingSrcCLR"
	include "SetSourceToItemsControl"
	include "XMLAsSource"
group ""
