XAMLOutputDir = os.getcwd()

group "CSharpFramework/WPF/XAML"
	include "AttributeEvent"
	include "HelloXAML"
	include "PropertyAssignment"
	include "TypeConverter"
	include "MarkupExtension"
	include "ControlLibrary"
	include "Xnamespace"
	include "CallDll"
	include "ContentControl"
	include "LayoutGrid"
	include "LayoutStackpanel"
	include "LayoutCanvas"
	include "LayoutDockPanel"
	include "LayoutWrapPanel"
	include "LayoutContent"
group ""
