group "CSharpFramework/WPF"
	include "src/WPF/ScottPlot"
	include "src/WPF/TreeViews"
	include "src/WPF/WPFBasics"
	include "src/WPF/HelloWPF"
group ""

group "CSharpFramework/WPF/XAML"
	include "src/WPF/XAML/ContentControl"
	include "src/WPF/XAML/HelloXAML"
	include "src/WPF/XAML/AttributeAssignment"
	include "src/WPF/XAML/XAMLOverview"
	include "src/WPF/XAML/MarkupExtension"
	include "src/WPF/XAML/ControlLibrary"
	include "src/WPF/XAML/CallDll"
	include "src/WPF/XAML/LayoutGrid"
	include "src/WPF/XAML/LayoutStackpanel"
	include "src/WPF/XAML/LayoutCanvas"
	include "src/WPF/XAML/LayoutDockPanel"
	include "src/WPF/XAML/LayoutWrapPanel"
	include "src/WPF/XAML/LayoutContent"
group ""

group "CSharpFramework/WPF/Binding"
	include "src/WPF/Binding/HelloBinding"
	include "src/WPF/Binding/ControlAsBindingSrc"
	include "src/WPF/Binding/ControlBindingDirAndDataUpdate"
	include "src/WPF/Binding/BindingPath"
	include "src/WPF/Binding/NoPathBinding"
group ""

group "CSharpFramework/WinForm"
	include "src/WinForm/HelloWindowsForms/"
group ""

include "src/WPF/Soscsrpg"
