group "CSharpFramework/WPF"
	include "src/WPF/ScottPlot"
	include "src/WPF/ContentControl"
	include "src/WPF/LayoutContent"
	include "src/WPF/TreeViews"
	include "src/WPF/WPFBasics"
	include "src/WPF/HelloWPF"
group ""

group "CSharpFramework/WPF/Layout"
	include "src/WPF/LayoutGrid"
	include "src/WPF/LayoutStackpanel"
	include "src/WPF/LayoutCanvas"
	include "src/WPF/LayoutDockPanel"
	include "src/WPF/LayoutWrapPanel"
group ""

group "CSharpFramework/WPF/XAML"
	include "src/WPF/XAML/HelloXAML"
	include "src/WPF/XAML/AttributeAssignment"
	include "src/WPF/XAML/XAMLOverview"
group ""

group "CSharpFramework/WinForm"
	include "src/WinForm/HelloWindowsForms/"
group ""
