group "CSharpFramework/WPF"
	include "src/WPF/HelloWPF"
	include "src/WPF/TreeViews"

	group "CSharpFramework/WPF/AngeISix"
		include "src/WPF/AngeISix/WPFBasics"
	group ""
group ""

group "CSharpFramework/WPF/XAML"
	include "src/WPF/XAML/AttributeEvent"
	include "src/WPF/XAML/HelloXAML"
	include "src/WPF/XAML/PropertyAssignment"
	include "src/WPF/XAML/TypeConvert"
	include "src/WPF/XAML/XAMLOverview"
	include "src/WPF/XAML/MarkupExtension"
	include "src/WPF/XAML/ControlLibrary"
	include "src/WPF/XAML/Xnamespace"
	include "src/WPF/XAML/CallDll"

	group "CSharpFramework/WPF/XAML/Control"
		-- layout control
		include "src/WPF/XAML/LayoutGrid"
		include "src/WPF/XAML/LayoutStackpanel"
		include "src/WPF/XAML/LayoutCanvas"
		include "src/WPF/XAML/LayoutDockPanel"
		include "src/WPF/XAML/LayoutWrapPanel"
		include "src/WPF/XAML/LayoutContent"

		-- content control
		include "src/WPF/XAML/ContentControl"
	group ""
group ""

group "CSharpFramework/WPF/Binding"
	include "src/WPF/Binding/ADO.NETAsBindingSource"
	include "src/WPF/Binding/HelloBinding"
	include "src/WPF/Binding/ControlAsBindingSrc"
	include "src/WPF/Binding/ControlBindingDirAndDataUpdate"
	include "src/WPF/Binding/MethodsForDefineSource"
	include "src/WPF/Binding/BindingPath"
	include "src/WPF/Binding/BindingSource"
	include "src/WPF/Binding/SetSourceToItemsControl"
	include "src/WPF/Binding/NoPathBinding"
	include "src/WPF/Binding/NoSourceBinding"
	include "src/WPF/Binding/NoPathSourceBinding"
	include "src/WPF/Binding/XMLAsSource"
group ""

group "CSharpFramework/WinForm"
	include "src/WinForm/HelloWindowsForms/"
group ""
